Feat 145
testproject-io/java-opensdk pull request #146
Opened 2021-07-05 14:24 UTC by oriddd

2021-07-05 16:05 UTC, mstrelex commented
@oriddd 

Can you please change the PR title to reflect the actual changes?

2021-07-05 16:36 UTC, mstrelex requested changes

2021-07-05 16:36 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/messages/Report.java
> +     * Should be Command / Test / Step.
Why not an enum if the list is closed?
And thus the classes `DriverCommandReport`, `StepReport`, and `TestReport` could define it as final constants.

2021-07-05 16:36 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/messages/Report.java
> +     * Used for json serialization.
GSON can serialize private fields, why a getter is required?

2021-07-05 16:36 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +    private static final String MIN_BATCH_REPORT_SUPPORTED_VERSION = "3.0.0";
Should be `3.1.0` as this is the version where it will be introduced first.

2021-07-05 16:36 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +    static final Logger LOG = LoggerFactory.getLogger(ReportsQueue.class);
ReportsQueue --> ReportsQueueBase

2021-07-05 16:36 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +    static final Logger LOG = LoggerFactory.getLogger(ReportsQueue.class);
Should have been split into a separate `refactor` commit to make it easier to understand whether there were any changes or not...

2021-07-05 16:36 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +                LOG.error("Failed to create json from list: [{}]", batchReports, e);
If it failed, shouldn't the method return?

2021-07-06 15:19 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/messages/DriverCommandReport.java
> +    private final String type = ReportItemType.Command.toString();
Still, why a string and not an enum?

2021-07-07 11:30 UTC, vitalybu requested changes

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> + * Copyright (c) 2020 TestProject LTD. and/or its affiliates
2021

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +import java.util.concurrent.*;
Do you really need all the classes from this package?
Usually it's better to import only what you actually use.

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +    private final ArrayBlockingQueue<ReportsQueue.QueueItem> queue = new ArrayBlockingQueue<>(1024 * 1024);
I think we already had a discussion about the size of this queue.
We don't really need an array with a million items, especially since it's pre-allocated.
@mstrelex, do you remember what was the decision?

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +    static final Logger LOG = LoggerFactory.getLogger(ReportsQueueBase.class);
`private static final`?

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +    static final Gson GSON = new GsonBuilder().create();
`private static final`?

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +    private static final int PROGRESS_REPORT_DELAY = 3;
Final members should be declared before any other members.

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +
Remove extra new line

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +     * Till version x -> send standalone report.
`version x`?

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +        while (this.running || queue.size() > 0) {
Why not `!this.queue.isEmpty()`?

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +        if (item.getRequest() == null && item.getReport() == null) {
Only if both are `null` it's considered as error?

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +        // Handle unsuccessful response
Maybe we should stop reporting after a certain number of errors?
For example, if the Agent crashed for some reason, the SDK will keep trying to report everything...

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +        // Handle unsuccessful response
Another case is if the Agent returns 401 or 403, this probably means that the development token is not valid, so there's no reason to continue reporting.

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +        this.queue.add(new QueueItem(null, null));
I don't understand why this is required.
Also it doesn't make sense sending nulls if it's "not possible"

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +     * Till version x -> send standalone report.
`version x`?

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +public class ReportsQueue extends ReportsQueueBase {
This class doesn't do much, why do we need it?

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> + * Copyright (c) 2020 TestProject LTD. and/or its affiliates
2021

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +    private List<Report> batchReports = new ArrayList<>();
Why `ArrayList` and not `LinkedList`?
Do we really array functionality?

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +    private static final int MAX_REPORTS_BATCH_SIZE = 10;
Maybe we should allow overriding the default using an environment variable (and/or some SDK option)

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +     * Till version x -> send standalone report.
`version x`?

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +        // extract and remove up to 10 items or till queue is empty from queue - without blocking it.
Comments should start from a capital letter

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +            } while (null != item && batchReports.size() < MAX_REPORTS_BATCH_SIZE);
Why?
It should report whatever is in the queue, up to the maximum allowed items.
We shouldn't wait for the items to accumulate in the qeueu.

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +            }
Previous comment for handling Agent response codes is relevant for this part as well

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +         * Test reporting endpoint address.
Not sure the comment is correct here

2021-07-07 11:30 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +     * Minimum Agent version that supports local reports.
... supports **batch** reports?

2021-07-07 12:33 UTC, oriddd commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +        if (item.getRequest() == null && item.getReport() == null) {
This behavior was exist. 
Once both are nulls and the queue is running -> this is an error.
The expected for both to be null is only once the queue is not running, this was defined to release the block for the queue.

2021-07-07 12:36 UTC, oriddd commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +        this.queue.add(new QueueItem(null, null));
This is the empty item that should release the queue.

2021-07-07 12:42 UTC, oriddd commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +public class ReportsQueue extends ReportsQueueBase {
This class is confirming that previous logic will still be exist.
In the original code - handleReport() method was not exist and the run() method was executed sendReport() method.
I've change the logic so that:
For version 3.1.0 and above -> handleReport() method will build ArrayList of reports and will send them as a batch.
For lower versions -> handleReport() method will perform the original logic.

2021-07-07 13:04 UTC, s-glatshtein commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +        this.queue.add(new QueueItem(null, null));
as the comment suggests, this will release the thread blocked by `queue.take()`. This is expected only when the queue is no longer running.

2021-07-07 13:07 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +        if (item.getRequest() == null && item.getReport() == null) {
And I left a comment on the "release" logic as well... I don't understand why it was designed this way.

2021-07-07 13:08 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +        this.queue.add(new QueueItem(null, null));
Can't we interrupt the thread instead of injecting an invalid value?

2021-07-07 13:09 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +public class ReportsQueue extends ReportsQueueBase {
But if the `ReportsQueue` doesn't actually add new logic, why not use the `ReportsQueueBase` for the old logic and override it in a new class for the new logic?

2021-07-07 15:10 UTC, mstrelex requested changes

2021-07-07 15:10 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +import java.util.concurrent.*;
I believe that when you work with IntelliJ, and you optimize the imports, it decides to put a wildcard after some specific threshold. This does not "include" the class, but just a way to tell Java where to find the definition of that class. There is no reason why not to put an asterisk, in order to reduce the number of imports.

2021-07-07 15:10 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> + * Copyright (c) 2020 TestProject LTD. and/or its affiliates
Same as my previous comment regarding the license header in general.

2021-07-07 15:10 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +        this.queue.add(new QueueItem(null, null));
This might be a better approach, but this is not a new code. It existed in this class before it was renamed, and unless you see some exotic negative consequences, I don't see a reason to modify it.

2021-07-07 15:10 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +    private List<Report> batchReports = new ArrayList<>();
https://stackoverflow.com/a/322742/712160

2021-07-07 15:10 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +    private static final int MAX_REPORTS_BATCH_SIZE = 10;
Maybe.

2021-07-07 15:10 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +        // extract and remove up to 10 items or till queue is empty from queue - without blocking it.
Agree.

2021-07-07 15:10 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +            } while (null != item && batchReports.size() < MAX_REPORTS_BATCH_SIZE);
Right, we should report anything there is or split it into chunks if it breaches the threshold.

2021-07-07 15:10 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +         * Test reporting endpoint address.
It's definitely not.

2021-07-07 15:10 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +     * Minimum Agent version that supports local reports.
Right.

2021-07-07 15:15 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +    private final ArrayBlockingQueue<ReportsQueue.QueueItem> queue = new ArrayBlockingQueue<>(1024 * 1024);
@vitalybu 

You said:

```
I'm not saying we need to have a queue with depth of 5 items, but 1k seems very reasonable to me. And no, returning an exception is not a good option, but maybe increasing the queue dynamically (up to some sane value) or even blocking the user in such a case, is a totally valid option.
If a user fills up the queue, maybe it's even better to block the calls to prevent flooding our backend.```

I answered:

```
Since there is a latency between the machine where the SDK is running and the Agent, this queue fills up, this is not the queue for reporting anything to the cloud but from the SDK to the Agent.
﻿﻿Indeed makes sense to refactor into LinkedBlockingQueue
﻿﻿﻿```
﻿﻿﻿
Previously we had a value of 1024 and it wasn't enough.
What would you like to specify here now?

2021-07-07 15:16 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +            }
I don't see this comment, what did you write there?

2021-07-07 15:32 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +    private final ArrayBlockingQueue<ReportsQueue.QueueItem> queue = new ArrayBlockingQueue<>(1024 * 1024);
If we'll switch to a dynamically allocated queue, let's go with a maximal value of 10k (assuming 1k wasn't enough).

2021-07-07 19:53 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +        // Handle unsuccessful response
This can be addressed in a separate PR, as this is not the purpose here.

2021-07-08 07:53 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/messages/ReportItemType.java
> + * Copyright (c) 2020 TestProject LTD. and/or its affiliates
Should be updated for new (or renamed) files as part of the PR modifying them...

2021-07-08 07:56 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +import java.util.concurrent.*;
You believe this is the case or is it really the case?
In any case, I'm not sure we want to rely on an IDE for this.
Importing an entire package can cause collisions with similar classes from different packages.
An IDE will probably detect and fix it automatically, but it's better to just import what is actually used.

2021-07-08 07:58 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +        // Handle unsuccessful response
If this logic wasn't added as part of this PR you're right.
But at least an issue should be created for this to be handled later.

2021-07-08 08:06 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +        this.queue.add(new QueueItem(null, null));
The negative consequences are extra logic that eventually can cause other issues and code that is harder to read/review... 
Personally, I consider something that needs to be explained by a three-line-comment and can be avoided, bad design.

2021-07-08 08:37 UTC, s-glatshtein commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +            } while (null != item && batchReports.size() < MAX_REPORTS_BATCH_SIZE);
Isn't this the case? either there's no item in queue (item is null) or the batch reaches 10 items (reportsSize == 10)

2021-07-08 11:02 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +    private List<Report> batchReports = new ArrayList<>();
We use it as a simple queue (push to the end and pull from the start), so a linked list is much more appropriate here.

2021-07-08 11:02 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +    private static final int MAX_REPORTS_BATCH_SIZE = 10;
Great, so let's do it

2021-07-08 11:06 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +            } while (null != item && batchReports.size() < MAX_REPORTS_BATCH_SIZE);
Maybe I'm unfamiliar with the queue syntax, but I understand this as if we're filling the `batchReports` with 10 items and only then report it to the Agent.
If the queue has only 5 items, I don't see a reason to wait for additional 5 to queue before reporting whatever is available to the Agent.

2021-07-08 11:07 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +            }
That we need to properly handle error response codes from the Agent.
There's no reason to keep reporting if the Agent returns 401, 403 or 500 for that matter... Maybe other codes as well.

2021-07-08 11:27 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/messages/ReportItemType.java
> + * Copyright (c) 2020 TestProject LTD. and/or its affiliates
It can't work that way, checkstyle has only one template to compare with.

2021-07-08 11:30 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +import java.util.concurrent.*;
I base my assumption on personal experience with IntelliJ.
I still don't understand what is the problem is everything compiles?
We can use a notepad that does not optimize anything on its own.

2021-07-08 11:33 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +import java.util.concurrent.*;
That's exactly the problem, sometimes it compiles but doesn't use the class we intended to use.
I remember more than one example of issues that were caused by using a class with the same name but from a different package.

2021-07-08 11:43 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/messages/ReportItemType.java
> + * Copyright (c) 2020 TestProject LTD. and/or its affiliates
You can probably use a regular expression in `checkstyle` to validate that there's a number in this place instead of a hard-coded value.

2021-07-08 11:45 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBase.java
> +import java.util.concurrent.*;
https://user-images.githubusercontent.com/5516364/124916289-1e48dc00-dfb8-11eb-8b8a-154cd8f93aa5.mp4

2021-07-08 11:50 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/messages/ReportItemType.java
> + * Copyright (c) 2020 TestProject LTD. and/or its affiliates
Indeed you are correct, there is such an option :)
https://github.com/testproject-io/java-opensdk/issues/147

2021-07-12 20:32 UTC, mstrelex requested changes

2021-07-12 20:32 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +     * In case of failure during report - attempt maximum 4 times.
This description is strange, why not just: `Maximum attempts to try sending a report to the Agent`?

2021-07-12 20:32 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +            if (response != null && response.getStatusLine().getStatusCode() != HttpURLConnection.HTTP_OK) {
It would be better checking all 2xx codes:
`response.getStatusInfo().getFamily().equals(Response.Status.Family.SUCCESSFUL)`

2021-07-12 20:32 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +                    LOG.error("Failed to send reports to the agent.");
Would be more informative: 

`LOG.error("All attempts ({}) sending report [{}] failed", MAX_REPORT_FAILURE_ATTEMPTS , item.getReport(), e);`

2021-07-12 20:32 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +                    throw new AgentConnectException("Failed to send reports to the agent.");
This is wrong, as the Agent did respond with some code. \
Maybe you want to add a new exception type? Or use `javax.ws.rs.core.Response.WebApplicationException`

2021-07-12 20:32 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +     * @throws InterruptedException
Missing explanation when and why this exception is thrown.

2021-07-12 20:32 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +                    LOG.error("Failed to submit report: [{}]", batchReports, e);
What will this print? Something like `List@ABC123` ?

2021-07-12 20:32 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +                if (response != null && response.getStatusLine().getStatusCode() != HttpURLConnection.HTTP_OK) {
Same comments as in the previous commit regarding 2xx status and error handling.

2021-07-12 20:32 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +            if (null != item && item.getReport() != null) {
And if they are null, don't you want to break the loop?

2021-07-13 12:21 UTC, mstrelex requested changes

2021-07-13 12:21 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +     * In case of failure during report - attempt maximum 4 times.
?

2021-07-13 12:21 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +    public ArrayBlockingQueue<QueueItem> getQueue() {
Why is it public? Anyone can remove items from the queue is accessed, can it be protected?
Also, a getter method standard description syntax is `Getter method for {@link #field}`

2021-07-13 12:21 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +     * Access method to get the httpClient.
Same as above.

2021-07-13 12:21 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +    private boolean brokenReports = false;
Can you think of a better name?

2021-07-13 12:21 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +     *  In case of 4 failures to send reports to the agent.
A proper description would be - `A flag that is raised when all attempts submitting a report fail.`

2021-07-13 12:21 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +                LOG.error("Attempt to send report again to the Agent. {} more attempts are left.", reportAttemptsCount);
Please change to warning log and the wording to:

`Failed to send a report to the Agent, {} attempts remaining...`

2021-07-13 12:21 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> + * Copyright (c) 2020 TestProject LTD. and/or its affiliates
Will be addressed in #147

2021-07-13 13:50 UTC, oriddd commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +            if (null != item && item.getReport() != null) {
I'm not sure. 
This check is to make sure the report isn't null - which we are not expecting to. 
We're except to get null only once adding the null item which was insert in order to release the queue.
In that case - the while condition is checking if the queue is empty - and the loop won't continue.

2021-07-13 14:11 UTC, oriddd commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +                    throw new AgentConnectException("Failed to send reports to the agent.");
I can't use that since javax.ws.rs.core.* is not included in the project.
Therefor I've created new Exception type for report failure.

2021-07-13 16:17 UTC, mstrelex requested changes

2021-07-13 16:17 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/exceptions/FailedReportException.java
> + * Exception object thrown when SDK is failed to send reports to the agent.
---> `This exception is thrown when SDK fails to send a report to the agent.`

2021-07-13 16:17 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/exceptions/FailedReportException.java
> +        this("Failed to send report to the Agent");
---> `Failed sending a report to the Agent`

2021-07-13 16:36 UTC, mstrelex requested changes

2021-07-13 16:36 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/AgentClient.java
> +     * Minimum Agent version that supports reporting at batches.
`Minimum Agent version that supports reporting at batches.` --> `Minimum Agent version that supports batch reporting.`

2021-07-13 16:36 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +    protected boolean isHTTPResponseSuccess(final CloseableHttpResponse response) {
Please do not reinvent the wheel, I already wrote to you how to do it the right way - `getStatusInfo().getFamily() != Family.SUCCESSFUL`

2021-07-13 16:36 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +    protected static final int LAST_SUCCESS_HTTP_STATUS = 299;
Irellevant, use `getStatusInfo().getFamily() == Family.SUCCESSFUL`

2021-07-13 16:36 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +     * Handle the report.
You are stating the obvious, this is not a summary, the same can be inferred from the method name.

2021-07-13 16:36 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +            if (isHTTPResponseSuccess(response)) {
`getStatusInfo().getFamily() == Family.SUCCESSFUL`

2021-07-13 16:36 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +            LOG.error("All {} attempts to send report {} are failed", MAX_REPORT_FAILURE_ATTEMPTS, item.getReport());
`All {} attempts to send report {} are failed` --> `All {} attempts to send report {} have failed`

2021-07-13 16:36 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +    private static final String TP_MAX_BATCH_SIZE = "TP_MAX_BATCH_SIZE";
`TP_MAX_BATCH_SIZE` ---> `TP_MAX_BATCH_SIZE_VARIABLE_NAME`

2021-07-13 16:36 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +                LOG.error("Attempt to send report again to the Agent. {} more attempts are left.", reportAttemptsCount);
Please change to INFO:

```
LOG.info("Retrying ({}) sending reports batch to the Agent...", MAX_REPORT_FAILURE_ATTEMPTS 
 - reportAttemptsCount);
 ```

2021-07-13 16:36 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +                LOG.error("All {} attempts to send report {} are failed", MAX_REPORT_FAILURE_ATTEMPTS, json);
You should not print the whole JSON in the error, what is it good for?

2021-07-14 00:10 UTC, mstrelex requested changes

2021-07-14 00:10 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +        } while (response != null && Response.Status.Family.familyOf(response.getStatusLine().getStatusCode())
Shouldn't it be `or`? While the response is null, or it's unsuccessful and there are more attempts left?

2021-07-14 00:13 UTC, mstrelex commented
Please adjust commit messages:

0f997ed9210102c583ac6eb79191103b12ccd9f4 --> `feat: Adding new route to support reports in batches.`
bcedcb9ae2cf560870d818fd153aff01f7c0ef12 --> `feat: Change QueueItem class to internal in order to use in additional classes.`
cc9e35d77c442ebf81f04d31517759a21222c9ac --> `feat: Prepare ReportsQueue class to be extended by adding new method … which can be overridden.`

2021-07-14 09:17 UTC, oriddd commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +        } while (response != null && Response.Status.Family.familyOf(response.getStatusLine().getStatusCode())
You're right. 
I've added this null check due to spotbug failures. 
Will change and commit as fixup.

2021-07-14 09:31 UTC, vitalybu requested changes

2021-07-14 09:31 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +    private static final String TP_MAX_BATCH_SIZE_VARIABLE_NAME = "TP_MAX_BATCH_SIZE";
`TP_MAX_BATCH_SIZE` --> `TP_MAX_REPORTS_BATCH_SIZE`

2021-07-14 09:31 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +        this.maxBatchSize = (System.getenv(TP_MAX_BATCH_SIZE_VARIABLE_NAME) != null)
Should surround this with a `try-catch` and use the default value on failure.

2021-07-14 09:31 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +
Remove empty line

2021-07-14 09:31 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +        if (!batchReports.isEmpty()) {
To reduce code indentation it's probably better to return from this method if `batchReports.isEmpty() == true`...

2021-07-14 09:31 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +                    batchReports.clear();
Why?

2021-07-14 09:31 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +            } while (response != null && Response.Status.Family.familyOf(response.getStatusLine().getStatusCode())
Should probably be ORs as @mstrelex mentioned before

2021-07-14 11:16 UTC, oriddd commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +                LOG.warn("Reports are disabled due to multiple failed attempts of sending reports to the agent.");
Before sending the reports - we are printing the exception message as an error. 
This warning is to let the user know that his reports are disabled from now on.
This warning was added to prevent bugs open due to missing reports in case of multiple failing attempts to report to the agent.

2021-07-14 11:33 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +                LOG.warn("Reports are disabled due to multiple failed attempts of sending reports to the agent.");
👍

2021-07-15 12:58 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +     * Progress report delay in seconds.
We don't delay the report, we have a delay between progress logs.
When the process using the SDK finishes, it logs how many reports are left to be reported.
To avoid noise in the log and too frequent progress reporting, we have a delay between the **progress** reports.

2021-07-15 16:37 UTC, mstrelex requested changes

2021-07-15 16:37 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +            LOG.info("Failed to retrieve the value of environment variable {}. "
Should be a warning and the last argument should be the exception.
What can go wrong here anyway? Failure to convert string to an integer?

2021-07-19 08:55 UTC, oriddd commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueueBatch.java
> +            LOG.info("Failed to retrieve the value of environment variable {}. "
You're right. 
The failure might be in:
1) SecurityException -  if a security manager exists and its checkPermission method doesn't allow access to the process environment (not expected to be that case).
2) Convert the string to an integer.

2021-07-19 13:28 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +    void sendReport(final HttpPost httpPost) throws FailedReportException {
Does this method should really be `public`?
If it's used internally, then it should be `protected`, no?

2021-07-19 13:45 UTC, oriddd commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +    void sendReport(final HttpPost httpPost) throws FailedReportException {
Right. 
Please correct me if I'm wrong, the default (without any modifier) is package-protect which should be more secure, no?

2021-07-19 14:16 UTC, vitalybu commented on src/main/java/io/testproject/sdk/internal/rest/ReportsQueue.java
> +    void sendReport(final HttpPost httpPost) throws FailedReportException {
You're right, forgot this is the default behavior in Java.
Let's leave it as is.

2021-07-26 16:19 UTC, mstrelex approved these changes

2021-07-26 17:42 UTC, vitalybu approved these changes

2021-07-26 17:47 UTC, mstrelex approved these changes

2021-07-26 17:47 UTC, merged