WIP: Support creating addons using the java OpenSDK
testproject-io/java-opensdk pull request #168
Opened 2021-12-21 15:11 UTC by s-glatshtein

This PR comes to implement all missing code required to develop and test an addon locally.

For it to be ready for review we must also add the following:

-  Clear example how to develop & test an addon action
-  Clear documentation explaining the flow of creating actions with the OpenSDK

2022-01-04 21:17 UTC, mstrelex requested changes

2022-01-04 21:17 UTC, mstrelex commented on src/test/java/io/testproject/sdk/tests/examples/addons/AddonsWithParameterTest.java
> +        TypeWithEnter action = new TypeWithEnter();
Perhaps renaming to `TypeWithEnterAction` would make more sense.

2022-01-04 21:17 UTC, mstrelex commented on src/test/java/io/testproject/sdk/tests/examples/addons/actions/TypeWithEnter.java
> +@WebAction(name = "Type & press Enter",
Do we really need all the annotations?
Perhaps we could have one annotation with a list of enums for the platforms?

2022-01-04 21:17 UTC, mstrelex commented on README.md
> +Addons are developed in Java and uploaded to the user’s account in a collaborative library. \
--> `Addons are developed in Java and uploaded to a collaborative library to the user’s account.`

2022-01-04 21:17 UTC, mstrelex commented on README.md
> +1. Download a manifest.
Perhaps can be done right before uploading, do we really need it to run in IDE?

2022-01-04 21:17 UTC, mstrelex commented on README.md
> +In order to build an Action that can be executed by TestProject, the class has to implement one of the interfaces that the SDK provides.\
Perhaps a hierarchy tree would be helpful here.

2022-01-04 21:17 UTC, mstrelex commented on README.md
> +The *run()* method returns *boolean* indicating if the action is passed.
... or throws an exception in case of a failure.

2022-01-04 21:17 UTC, mstrelex commented on README.md
> + * To prevent it from being available for mobile, we add the WebAction annotation.
What about Chrome on Android for example?

2022-01-04 21:17 UTC, mstrelex commented on README.md
> +    Types a random phone number in the requested element.
Why the indentation suddenly? None on line 1063.

2022-01-04 21:17 UTC, mstrelex commented on README.md
> +    public boolean run(final RemoteWebDriver driver, final By elementSearchCriteria) {
Why a `RemoteWebDriver` and not the interface `WebDriver`?

2022-01-04 21:17 UTC, mstrelex commented on README.md
> + 1. There are 3 action annotations, 1 per platform: **WebAction**, **AndroidAction** and **IOSAction**.\
As proposed earlier let's consider one with a list or array of enums.

2022-01-04 21:17 UTC, mstrelex commented on README.md
> +This JAR must contain all the dependencies (including TestProject SDK) and your action, but not your tests. \
Well, that's a serious issue.... each action will be very heavy.
I think we ignored this part when we discussed the design.
Perhaps we do want to find a solution? @eldarkra ideas?

2022-01-05 08:22 UTC, eldarkra commented on README.md
> +This JAR must contain all the dependencies (including TestProject SDK) and your action, but not your tests. \
Why does it have to contain the SDK?

2022-01-05 08:51 UTC, s-glatshtein commented on README.md
> +This JAR must contain all the dependencies (including TestProject SDK) and your action, but not your tests. \
We had a constant issue with the old SDK having to be very version dependent and hard to support backwards.
For OpenSDK we decided that users will upload the SDK with each bundle to remove this dependency (@vitalybu was involved with this decision as well as @mstrelex). I simply followed the decided behavior

2022-01-05 08:52 UTC, s-glatshtein commented on src/main/java/io/testproject/sdk/internal/addons/AddonsHelper.java
> +        return execute(action, -1);
The test's default step timeout. This wasn't a new value, I just moved the methods around a little bit :)

2022-01-05 08:54 UTC, s-glatshtein commented on src/main/java/io/testproject/sdk/internal/addons/AddonsHelper.java
> +        action.getDescriptor().setBy(by);
This commit was intended to re-organize the proxy execute methods to generic and non-generic executions to move the ones without elements to the GenericAddonsHelper class. How should I change this commit to make it more clear?

2022-01-05 08:54 UTC, s-glatshtein commented on src/main/java/io/testproject/sdk/internal/addons/interfaces/Action.java
> + * Copyright 2021 TestProject LTD. and/or its affiliates
It wasn't when I did the commits :(

2022-01-05 08:55 UTC, s-glatshtein commented on src/main/java/io/testproject/sdk/internal/addons/GenericAddonsHelper.java
> +    private Object convertToType(final Class<?> clazz, final String value) {
It is used to set the output value of the proxy action in line 120 of the same file:
```java
            // Use reflection to set the output value
            proxyField.get().setAccessible(true);
            try {
                proxyField.get().set(action, convertToType(proxyField.get().getType(), (String) field.getValue()));
            } catch (IllegalAccessException e) {
                LOG.error("Failed to set field [{}] value to [{}]", field.getName(), field.getValue());
            }
```

2022-01-05 08:56 UTC, s-glatshtein commented on README.md
> + * To prevent it from being available for mobile, we add the WebAction annotation.
There's an example below for each platform

2022-01-05 08:57 UTC, s-glatshtein commented on README.md
> +    public boolean run(final RemoteWebDriver driver, final By elementSearchCriteria) {
Good idea. I will fix it in the docs and the example

2022-01-05 09:00 UTC, s-glatshtein commented on README.md
> +    Types a random phone number in the requested element.
Will reduce the spaces. One of those is probably copied from a place with proper indentation

2022-01-05 09:51 UTC, s-glatshtein commented on src/test/java/io/testproject/sdk/tests/examples/addons/actions/TypeWithEnter.java
> +@WebAction(name = "Type & press Enter",
We could, but do you think it would make the code more readable? Or would be easier for users to understand how to use?

2022-01-05 09:53 UTC, s-glatshtein commented on README.md
> +1. Download a manifest.
I'll reorder it so this is 3rd, as well as reorder the sections in the readme

2022-01-05 09:54 UTC, s-glatshtein commented on README.md
> +In order to build an Action that can be executed by TestProject, the class has to implement one of the interfaces that the SDK provides.\
I do not understand what you mean. Can you please add more details?

2022-01-05 09:55 UTC, s-glatshtein commented on README.md
> +The *run()* method returns *boolean* indicating if the action is passed.
I'll add that it will also fail if an exception is thrown

2022-02-01 01:46 UTC, mstrelex requested changes

2022-02-01 01:46 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/addons/interfaces/GenericAction.java
> +    boolean run(ReportingDriver driver);
Can we somehow create a symbolic link or anything similar for a non-driver action at all?
This could be great to "hide" it and make it implicit toward API automation for example.

2022-02-01 01:46 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/addons/GenericAddonsHelper.java
> +     * <a href="https://app.testproject.io/#/addons">TestProject</a> App.
Is that a valid javadoc? GitHub highlights it as an error....

2022-02-01 01:46 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/addons/annotations/AddonAction.java
> + * Marks the action as a web action.
Not necessarily a web action, but based on the platform.

2022-02-01 01:46 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/addons/annotations/GenericAction.java
> +public @interface GenericAction {
Remind me please, why do we have `GenericAction` and also `AddonAction`,
can't we just have `AddonAction` with all the platforms, or just one - `Any`?

2022-02-01 01:46 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/addons/Platform.java
> +/*
`Platform`, `AddonAction` and `GenericAction` are not internal enums.
They are actually public ones that we want the users to use.

2022-02-01 01:46 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/addons/ParameterDirection.java
> +/*
`ParameterDirection ` and `Parameter` not internal enums.
They are actually public ones that we want the users to use.

2022-02-01 01:46 UTC, mstrelex commented on src/test/java/io/testproject/sdk/tests/examples/addons/actions/ClearFieldsAndroid.java
> +public final class ClearFieldsAndroid implements Action<AndroidDriver<WebElement>> {
Perhaps would be best if will be suffixed with `Action`

2022-02-01 01:46 UTC, mstrelex commented on src/test/java/io/testproject/sdk/tests/examples/addons/actions/ClearFieldsWeb.java
> +@AddonAction(platforms = Platform.Web, name = "Clear Fields")
Perhaps would be best if will be suffixed with `Action`

2022-02-01 01:46 UTC, mstrelex commented on README.md
> +In order to build an Action that can be executed by TestProject, the class has to implement one of the interfaces that the SDK provides.\
My comment is still relevant.

2022-02-01 01:46 UTC, mstrelex commented on README.md
> +<details><summary>IOS Action</summary>
`IOS` --> `iOS`

2022-02-01 01:46 UTC, mstrelex commented on README.md
> + * Types a random phone number in the requested element.
Huh?

2022-02-01 01:46 UTC, mstrelex commented on README.md
> + * This action is the same for all platforms, and therefore uses Selenium's RemoteWebDriver with no annotations.
Driver?

2022-02-01 01:46 UTC, mstrelex commented on README.md
> +    * **version** - A version string which is used for future reference.
Where and why do we have a version in `AddonAction` ?

2022-02-01 01:46 UTC, mstrelex commented on README.md
> +    * **platforms** - A _mandatory_ field that explains which platform this action applies to.
platform`S`

2022-02-01 01:46 UTC, mstrelex commented on README.md
> +    * **defaultValue** - Defines a default value that will be used for the parameter.
Where is `optionall()`?

2022-02-01 01:46 UTC, mstrelex commented on README.md
> +This JAR must contain all the dependencies (including TestProject SDK) and your action, but not your tests. \
We decided to separate the SDK from the compiled addon.

2022-02-01 01:46 UTC, mstrelex commented on README.md
> +This JAR must contain all the dependencies (including TestProject SDK) and your action, but not your tests. \
Please change, it no longer has to include the SDK.

2022-02-01 01:46 UTC, mstrelex commented on README.md
> +    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
Still relevant when we extract the SDK?

2022-02-01 01:46 UTC, mstrelex commented on README.md
> +                    <descriptor>src/main/java/assembly/jar-with-dependencies.xml</descriptor>
Still relevant when we extract the SDK?

2022-02-01 01:46 UTC, mstrelex commented on README.md
>  Here are more [examples](/src/test/java/io/testproject/sdk/tests/examples):
Where is the Gradle/Maven config to include dependencies and strip the SDK?

2022-02-01 07:31 UTC, s-glatshtein commented on src/main/java/io/testproject/sdk/internal/addons/GenericAddonsHelper.java
> +     * <a href="https://app.testproject.io/#/addons">TestProject</a> App.
i moved it from the existing javadoc, so didn't see these tags. i'll fix the javadoc

2022-02-01 07:31 UTC, s-glatshtein commented on src/main/java/io/testproject/sdk/internal/addons/annotations/AddonAction.java
> + * Marks the action as a web action.
Indeed these are leftovers. Will fix

2022-02-01 07:32 UTC, s-glatshtein commented on src/main/java/io/testproject/sdk/internal/addons/annotations/GenericAction.java
> +public @interface GenericAction {
I thought I removed this :( removing now

2022-02-01 08:14 UTC, s-glatshtein commented on src/main/java/io/testproject/sdk/internal/addons/interfaces/GenericAction.java
> +    boolean run(ReportingDriver driver);
I didn't understand what you meant by symbolic link, but I assume you mean that API-only calls don't require a driver?
I think that any TP action requires a session to work (same as generic tests), but the action itself can only use the reporter to send the result. 
Please let me know if I misunderstood your intention.

2022-02-01 13:36 UTC, s-glatshtein commented on README.md
> +    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
yes, it collects all dependencies except the SDK, which is compileOnly (updated on the top)

2022-02-01 13:36 UTC, s-glatshtein commented on README.md
> +                    <descriptor>src/main/java/assembly/jar-with-dependencies.xml</descriptor>
It is how you create the uber jar with all dependencies except the SDK

2022-02-01 13:37 UTC, s-glatshtein commented on README.md
>  Here are more [examples](/src/test/java/io/testproject/sdk/tests/examples):
Added to gradle how to include all but SDK, and add the properties file as well

2022-02-01 15:09 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/addons/interfaces/GenericAction.java
> +    boolean run(ReportingDriver driver);
Yes, the driver is redundant.
Perhaps something that is named as `AutomationSession` that wraps an AgentClient init...

2022-02-02 12:45 UTC, mstrelex commented on src/main/java/io/testproject/sdk/internal/addons/interfaces/GenericAction.java
> +    boolean run(ReportingDriver driver);
Let's stay with the `GenericDriver` for now.

2022-02-02 12:46 UTC, mstrelex approved these changes

2022-02-02 14:06 UTC, merged