build: add GitHub actions to upload to the release artifacts a full jar and md5 file
testproject-io/java-opensdk pull request #172
Opened 2022-01-27 10:01 UTC by oriddd

Solving issue #171

2022-01-27 17:25 UTC, mstrelex requested changes

2022-01-27 17:25 UTC, mstrelex commented on build.gradle
> +// Add the fullJar task to the build lifecycle.
Rename `fullJar`

2022-01-27 17:25 UTC, mstrelex commented on .github/workflows/build.yml
> +    - name: Define FULL jar name
This is a pure CI commit, it's not `build:`, it's `ci:`
Also, this should not be part of the build workflow, but a separate workflow that is triggered when the SDK is published.

Please adjust the commit messages and the description as well.
Rename Full Jar to uberJAR

2022-01-27 17:25 UTC, mstrelex commented on .github/workflows/build.yml
> +        export TP_SDK_FULL_JAR_EXT="FULL.jar"
No need for the `FULL` suffix.

2022-01-27 17:25 UTC, mstrelex commented on .github/workflows/build.yml
> +        export TP_SDK_VARIANT="SNAPSHOT"
No need to publish uberJAR for SNAPSHOT releases.

2022-01-27 17:25 UTC, mstrelex commented on .github/workflows/build.yml
> +      if: startsWith(github.ref, 'refs/tags/v')
Can be removed if the whole flow runs on published releases only.

2022-01-27 17:25 UTC, mstrelex commented on .github/workflows/build.yml
> +    - name: Upload FULL jar to release
Rename, please.

2022-01-27 17:25 UTC, mstrelex commented on .github/workflows/build.yml
> +        md5sum build/libs/${{ env.TP_SDK_JAR_NAME }}-${{ env.TP_SDK_VERSION }}-${{ env.TP_SDK_VARIANT}}-${{ env.TP_SDK_FULL_JAR_EXT }} > build/libs/jar-hash.md
Why save the hash to file and not variable?

2022-01-27 17:32 UTC, s-glatshtein commented on build.gradle
>      }
@mstrelex there is such a thing and it applies to gradle changes only
@oriddd that means your commit fixing the github build script should be `ci:` and not `build`

2022-01-30 09:22 UTC, oriddd commented on build.gradle
> +    archiveFileName = project.name + "-" + project.version + "-FULL.jar"
This file (without the suffix) already exists (since the jar task is creating it). 
I'll replace the "FULL" suffix with "UBER"

2022-01-30 10:14 UTC, oriddd commented on .github/workflows/build.yml
> +        export TP_SDK_FULL_JAR_EXT="FULL.jar"
Please see my comment: 
https://github.com/testproject-io/java-opensdk/pull/172/commits#r793807676

2022-01-30 10:21 UTC, oriddd commented on .github/workflows/build.yml
> +        md5sum build/libs/${{ env.TP_SDK_JAR_NAME }}-${{ env.TP_SDK_VERSION }}-${{ env.TP_SDK_VARIANT}}-${{ env.TP_SDK_FULL_JAR_EXT }} > build/libs/jar-hash.md
According to the architecture, we need to compare the SDK uber jars according to the md5 hash. 
This md5 hash is saved as an artifact to avoid downloading the whole jar and calculating the hash each time.

2022-01-30 16:33 UTC, oriddd commented on .github/workflows/build.yml
> +      if: startsWith(github.ref, 'refs/tags/v')
@mstrelex 
Please review the example I've created in the private repository: 
https://github.com/oriddd/java-opensdk/tree/master/.github/workflows 

- The **build.yml** is a reusable workflow.

- The **build_snapshot.yml** is getting triggered by every commit and running the build.yml. 

- The **build_release.yml** is getting triggered only once a release is created. 
It's running the buid.yml and adding another logic after that. 

The main issue is: 
Those 2 jobs are running on separate runner machines and the second job (that needs to upload the uberJAR file) doesn't have this jar and must to re-build it.  
Do you have any idea how can we solve that problem without re-building (running grade build again)?

2022-02-01 11:36 UTC, oriddd commented
@mstrelex @s-glatshtein  
This is currently blocked by https://github.community/t/ref-head-in-reusable-workflows/203690/67 
Will create new PR with the old approach that has 1 workflow file with actions that are running only for release. 
Marking this PR as WIP for future changes once the bug will be fixed.

2022-02-02 17:30 UTC, mstrelex requested changes

2022-02-02 17:30 UTC, mstrelex commented on build.gradle
> +    archiveFileName = project.name + "-" + project.version + "-UBER.jar"
Why do we need the suffix? `-UBER.jar`

2022-02-03 15:09 UTC, mstrelex commented on build.gradle
> +    archiveFileName = project.name + "-" + project.version + "-FULL.jar"
I understand now. The Standard IMHO is something lower case, e.g. `jar-with-dependencies`

2022-02-03 15:17 UTC, oriddd commented on build.gradle
> +    archiveFileName = project.name + "-" + project.version + "-FULL.jar"
It's changed as part of: https://github.com/testproject-io/java-opensdk/pull/173 
The changes on build.gradle file were removed from this PR :)

2022-02-03 16:52 UTC, closed without merging